/**
 * One-off/regenerable script that derives evolution-family groupings from
 * pokemon-go-api's own pokedex feed (the same source `sync.ts` uses for the
 * catalog) and writes them out as the frontend's `POKEMON_FAMILY_ID`
 * constant. Each `RawPokemon` entry's `evolutions[].id` is a forward-only
 * edge to its next evolutionary stage(s) (see the doc comment on
 * `RawEvolution` in transform.ts) — this script unions those edges into
 * connected components via union-find, so e.g. Pichu/Pikachu/Raichu all end
 * up sharing one family id (the lowest dex number in the chain).
 *
 * Run with `npm run generate:pokemon-family` whenever a new generation's
 * Pokemon are added to the feed.
 */
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { RawPokemon } from './transform.js';

const POKEDEX_URL = 'https://pokemon-go-api.github.io/pokemon-go-api/api/pokedex.json';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(
  __dirname,
  '..',
  '..',
  'src',
  'app',
  'core',
  'services',
  'pokemon-family.constant.ts'
);

class UnionFind {
  private readonly parent = new Map<number, number>();

  add(id: number): void {
    if (!this.parent.has(id)) {
      this.parent.set(id, id);
    }
  }

  find(id: number): number {
    const parent = this.parent.get(id);
    if (parent === undefined) {
      throw new Error(`Unknown id in union-find: ${String(id)}`);
    }
    if (parent !== id) {
      const root = this.find(parent);
      this.parent.set(id, root);
      return root;
    }
    return id;
  }

  union(a: number, b: number): void {
    const rootA = this.find(a);
    const rootB = this.find(b);
    if (rootA !== rootB) {
      this.parent.set(Math.max(rootA, rootB), Math.min(rootA, rootB));
    }
  }
}

async function fetchPokedex(): Promise<RawPokemon[]> {
  const response = await fetch(POKEDEX_URL);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch pokedex.json: ${String(response.status)} ${response.statusText}`
    );
  }
  return (await response.json()) as RawPokemon[];
}

function buildFamilyIdByName(pokedex: RawPokemon[]): Record<string, number> {
  const dexNrById = new Map(pokedex.map((pokemon) => [pokemon.id, pokemon.dexNr]));
  const unionFind = new UnionFind();

  for (const pokemon of pokedex) {
    unionFind.add(pokemon.dexNr);
  }

  for (const pokemon of pokedex) {
    for (const evolution of pokemon.evolutions) {
      const targetDexNr = dexNrById.get(evolution.id);
      if (targetDexNr !== undefined) {
        unionFind.union(pokemon.dexNr, targetDexNr);
      }
    }
  }

  const familyIdByName: Record<string, number> = {};
  for (const pokemon of pokedex) {
    familyIdByName[pokemon.names.English] = unionFind.find(pokemon.dexNr);
  }
  return familyIdByName;
}

function renderConstantFile(familyIdByName: Record<string, number>): string {
  const sortedNames = Object.keys(familyIdByName).sort(
    (a, b) => familyIdByName[a] - familyIdByName[b] || a.localeCompare(b)
  );
  const entries = sortedNames
    .map((name) => `  ${JSON.stringify(name)}: ${String(familyIdByName[name])},`)
    .join('\n');

  return `/* cSpell:disable */
/**
 * Generated by \`npm run generate:pokemon-family\` (server/src/generate-pokemon-family.ts)
 * from pokemon-go-api's pokedex feed — do not hand-edit. Maps each species'
 * plain root name to a family id shared with every other member of its
 * evolutionary line (the id is the lowest national dex number in the
 * family, chosen for stability, not significance).
 */
export const POKEMON_FAMILY_ID: Record<string, number> = {
${entries}
};
`;
}

async function main(): Promise<void> {
  console.log('Fetching pokedex.json from pokemon-go-api...');
  const pokedex = await fetchPokedex();
  console.log(`Fetched ${String(pokedex.length)} species entries.`);

  const familyIdByName = buildFamilyIdByName(pokedex);
  const familyCount = new Set(Object.values(familyIdByName)).size;
  console.log(
    `Grouped ${String(Object.keys(familyIdByName).length)} species into ${String(familyCount)} families.`
  );

  await writeFile(OUTPUT_PATH, renderConstantFile(familyIdByName));
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err: unknown) => {
  console.error('generate-pokemon-family failed:', err);
  process.exitCode = 1;
});
