import assert from 'node:assert/strict';
import test from 'node:test';

import {
  VARIANTS,
  buildEnvironmentIosSource,
  generateEnvironmentIos,
  resolveLocalBackendOrigin,
  resolveProdBackendOrigin,
} from './write-environment-ios.mjs';

test('resolveLocalBackendOrigin prefers IOS_BACKEND_ORIGIN_LOCAL when set', () => {
  const origin = resolveLocalBackendOrigin({
    IOS_BACKEND_ORIGIN_LOCAL: 'http://10.0.0.5:9999',
  });

  assert.equal(origin, 'http://10.0.0.5:9999');
});

test('resolveLocalBackendOrigin composes from auto-detected LAN host + fixed port 3000', () => {
  const origin = resolveLocalBackendOrigin(
    {},
    {
      networkInterfaces: () => ({
        en0: [{ family: 'IPv4', internal: false, address: '192.168.0.21' }],
      }),
    }
  );

  assert.equal(origin, 'http://192.168.0.21:3000');
});

test('resolveLocalBackendOrigin throws a clear error when no LAN host can be found', () => {
  assert.throws(
    () =>
      resolveLocalBackendOrigin(
        {},
        {
          networkInterfaces: () => ({
            lo0: [{ family: 'IPv4', internal: true, address: '127.0.0.1' }],
          }),
        }
      ),
    /Unable to auto-detect a LAN IP/
  );
});

test('resolveProdBackendOrigin prefers IOS_BACKEND_ORIGIN_PROD over BACKEND_ORIGIN', () => {
  const origin = resolveProdBackendOrigin({
    IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com',
    BACKEND_ORIGIN: 'https://fallback.example.com',
  });

  assert.equal(origin, 'https://prod.example.com');
});

test('resolveProdBackendOrigin falls back to BACKEND_ORIGIN', () => {
  const origin = resolveProdBackendOrigin({ BACKEND_ORIGIN: 'https://fallback.example.com' });

  assert.equal(origin, 'https://fallback.example.com');
});

test('resolveProdBackendOrigin throws a clear error when neither env var is set', () => {
  assert.throws(() => resolveProdBackendOrigin({}), /IOS_BACKEND_ORIGIN_PROD.*required/);
});

test('buildEnvironmentIosSource emits a minimal generated environment file', () => {
  const source = buildEnvironmentIosSource({
    production: false,
    apiUrl: 'http://192.168.0.21:3000',
  });

  assert.match(source, /Generated by scripts\/write-environment-ios\.mjs — do not edit\./);
  assert.match(source, /production: false,/);
  assert.match(source, /apiUrl: 'http:\/\/192\.168\.0\.21:3000',/);
});

test('generateEnvironmentIos writes the local variant to its output path', () => {
  let written = null;
  const result = generateEnvironmentIos({
    variant: 'local',
    envValues: { IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.0.21:3000' },
    writeFileSyncFn: (path, contents) => {
      written = { path, contents };
    },
  });

  assert.equal(result.outputPath, VARIANTS.local.outputPath);
  assert.equal(written.path, VARIANTS.local.outputPath);
  assert.match(written.contents, /apiUrl: 'http:\/\/192\.168\.0\.21:3000',/);
  assert.match(written.contents, /production: false,/);
});

test('generateEnvironmentIos writes the prod variant to its output path', () => {
  let written = null;
  const result = generateEnvironmentIos({
    variant: 'prod',
    envValues: { IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com' },
    writeFileSyncFn: (path, contents) => {
      written = { path, contents };
    },
  });

  assert.equal(result.outputPath, VARIANTS.prod.outputPath);
  assert.match(written.contents, /apiUrl: 'https:\/\/prod\.example\.com',/);
  assert.match(written.contents, /production: true,/);
});

test('generateEnvironmentIos rejects an unknown variant', () => {
  assert.throws(
    () => generateEnvironmentIos({ variant: 'staging' }),
    /Unknown iOS environment variant/
  );
});
